### ISSUE TITLE
Investigate supporting 'extensible' enums.

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/bicep-types-az#310]
Now that we're onboarded to the latest autorest, we have the ability to distinguish between 'closed' & 'open' enums. We should consider supporting this in our type system.

**Comment by anthony-c-martin** [comment]
Possibly related: https://github.com/Azure/bicep/issues/3817 - use of a CSV list of enums raises a warning.

**Comment by anthony-c-martin** [comment]
Possibly related: https://github.com/Azure/bicep/issues/4064

**Comment by jeskew** [comment]
Supporting extensible enums may be as simple as distinguishing in [`parseEnumType`](https://github.com/Azure/bicep-types-az/blob/2d4e08cf2493528def3f32c45d8b740ed2b0965f/src/autorest.bicep/src/type-generator.ts#L465-L484) between `ChoiceSchema` and `SealedChoiceSchema` objects. [@autorest/codemodel](https://github.com/Azure/autorest/blob/a5b47c3c214adb65d3cf2ae221c58cca5781a164/packages/extensions/modelerfour/src/modeler/modelerfour.ts#L714) will use `SealedChoiceSchema` if an enum's `modelAsString` property is set to `false` (per [the Autorest docs](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-enum), this indicates that the enum is closed) and `ChoiceSchema` otherwise.

For any `ChoiceSchema` passed to `parseEnumType`, the non-literal string type would be added to the union type defined for the enum.

**Comment by anthony-c-martin** [comment]
Note that there's also the question of how we fit this into Bicep. I assume we could represent open enums as e.g. `'foo' | 'bar' | string`, but we'd need to make sure language features such as completions work well with this, and that we don't accidentally coerce the type down to `string`. Feels like it's bound to break in a number of places without some work.

We should also think about whether we want to support the common convention of using a CSV-formatted list to support a multi-choice enum (e.g. `'foo, bar'`). I'd personally say "no", but I think it's worthy of a discussion.

**Comment by jeskew** [comment]
[Bicep does coerce the type down to `string` when loading the type](https://github.com/Azure/bicep/blob/bbca95af0e4f41e4e94f1cc2c1a76babef3ae030/src/Bicep.Core/TypeSystem/TypeHelper.cs#L70-L74), but I was able to get completions working by removing the explicit downcast:

![completions](https://user-images.githubusercontent.com/705500/169122722-32371b23-170f-44cd-8a3e-f8dc8daea34f.gif)

I'm not sure I follow the comment about the CSV-formatted list. Would that be how we should display the type signature for a multi-choice enum (instead of however it shows now, presumably something like `Array<'foo'|'bar'>`)?
