### ISSUE TITLE
Meaning of DeployTimeConstant flag?

### ISSUE THREAD

**Issue by rjmholt** [Azure/bicep-types-az#32]
I'm just looking at the `ObjectPropertyFlags` on various types and I feel like most of them are relatively self-explanatory (although if you've got time I'd love a description of all of them), but I'm curious about `DeployTimeConstant` -- what does that signify?

For reference I'm talking about this enum:

https://github.com/Azure/bicep-types-az/blob/4148b8da4f55fe8e4104c7e1a1f8301e120806cc/src/Bicep.SerializedTypes/Concrete/ObjectType.cs#L17-L29

**Comment by majastrz** [comment]
In our runtime, expressions are evaluated at the beginning of the deployment and during the deployment of each individual resource. The latter part is used to evaluate functions like listKeys() or reference() because the return value may depend on resources that were deployed by the same template.

If a property of a resource has the `DeployTimeConstant` flag, it means that expressions containing those functions cannot be assigned to the property. In other words, the expression has to evaluate upfront without dependencies on other resources and remains a constant during the deployment of the resource.

**Comment by anthony-c-martin** [comment]
Closing this out - feel free to raise a new issue if you've got any other questions!
